[package]
name = "awablock"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.0"
serde = "1.0.188"
futures = "0.3.28"
tokio = {version = "1.32.0", features = ["full"]}
mongodb = {version = "3.0.1"}
